---
name: intel SceneC lassification
author: ChangeBio
description: Seventeen flowers classfication
topic: intel SceneC lassification
algorithm: DenseNet121
language: python3
virtualenv: flyai_env/bin/

framework: Pretrained

data:
  id: intelSceneClassification
  name: intel SceneC lassification
  category: image


model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: string
    to_type: float
    to_shape: [-1,224, 224, 3]
  output:
    columns:
      - name: label
        type: int
    to_type: float
    to_shape: [-1,6]
  transfer_learning: 'https://download.pytorch.org/models/densenet121-241335ed.pth'


evaluate:
  score: torch_accuracy

servers:
 - id: flyai
   url: https://flyai.com
...