---
id: HumanFaceKeyPointDetection
name: 人脸关键点检测
author: jiery
description: 人脸关键点检测
topic: topic
algorithm: MLP
language: python3
virtualenv: flyai_env/bin/

framework: tensorflow


data:
  id: HumanFaceKeyPointDetection
  name: 人脸关键点检测
  author: jiery
  category: image

model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: url
    to_type: float
    to_shape: [178,178,3]

  output:
    columns:
      - name: p1
        type: int
      - name: p2
        type: int
      - name: p3
        type: int
      - name: p4
        type: int
      - name: p5
        type: int
      - name: p6
        type: int
      - name: p7
        type: int
      - name: p8
        type: int
      - name: p9
        type: int
      - name: p10
        type: int
    to_type: float
    to_shape: [10]

servers:
 - id: flyai
   url: https://flyai.com
...