---
# 项目的名字
name: 呼吸音推断呼吸系统疾病
# 项目的作者
author: M
# 项目的描述
description: 这个数据集为语音命令识别（speech command），识别12个类别的语音，包括10种语音命令、静音以及其他语音的。数据集包含了超过2万多的语音文件。
# 项目的主题
topic: 语音分类
# 项目使用的网络j
algorithm: CNN
language: Python3
virtualenv: flyai_env/bin/
# 项目使用的框架
framework: tensorflow

# 使用的数据集
data:
  # 数据集id
  # 该id为上传数据生成的id
  # 通过该id下载可以对应的数据集
  id: RespiratorySound
  name: 呼吸音推断呼吸系统疾病
  category: nlp

# 数据模型
model:
  # 数据处理类
  # 通过python的反射，生成该对象
  processor: Processor
  # 输入x数据处理的方法
  # 通过反射调用，可以修改名字
  input_x: input_x
  # 输入y数据处理的方法
  # 通过反射调用，可以修改名字
  input_y: input_y
  # 模型输出y数据处理的方法
  # 通过反射调用，可以修改名字
  output_y: output_y
  # 模型用到的输入x字段
  # 在processor.py的input_x方法中体现
  input:
    columns:
      - name: audio_and_txt_files_path
        type: string
      - name: patient_id
        type: int
      - name: age
        type: int
      - name: sex
        type: string
      - name: adult_bmi
        type: int
      - name: child_weight
        type: int
      - name: child_height
        type: int
    # 最终转换的数据类型
    to_type: int
    # 最终转换的数据纬度
    to_shape: (MAX_LEN,)
  # 模型用到的输入y字段
  # 在processor.py的input_y方法中体现
  output:
    columns:
      - name: diagnosis
        type: string
    # 最终转换的数据类型
    to_type: int
    # 最终转换的数据维度
    to_shape: (MAX_LEN,)

# 使用离线训练的服务器
servers:
 - id: flyai
   url: https://flyai.com
...