---
name: CIFAR10图片分类
author: jiayi
description: CIFAR10种图片分类
topic: CIFAR10种图片分类
algorithm: CNN
language: python3.6
virtualenv: flyai_env/bin/

framework: keras


data:
  id: CIFAR10
  name: CIFAR10种图片分类数据
  category: image

model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: url
    to_type: float
    to_shape: [-1,32,32,3]
  output:
    columns:
      - name: label
        type: int
    to_type: int
    to_shape: [-1,10]

evaluate:
  score: keras_accuracy
servers:
  - id: flyai
    url: https://flyai.com
...